POST http://localhost:3000/user/register
content-type:application/x-www-form-urlencoded

username=jiaxin&password=123456&code=secb

###
POST http://localhost:3000/user/login
content-type:application/x-www-form-urlencoded

username=wbeilbbpx3&password=111111&code=73p2
###
GET http://localhost:3000/user/personal
Authorization: yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndiZWlsYmJweCIsInVpZCI6IjlkYzc0NDY2LTMxMDEtMTFlOS04NTBjLWUwYWNjYjcxOTEwMCIsImlhdCI6MTYxMDYxMTg1OCwiZXhwIjoxNjEwNjExOTE4fQ.ioQDeNqAByh5o8klNEBE2XOFv7PlVIuAqPAcR8Dfr9Q


### 
GET http://localhost:3000/user/getcode
